
spring:
    application:
        name: map-report-backend
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

# CORS Configuration
cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

server:
    port: 8080
---
openbuildright:
    reportmapper:
        objectstore:
            image:
                max-width: 1280
                max-height: 1280
                normalize-image: true
            minio:
                bucket: dev
                access-key: minio_root_user
                secret-key: minio_root_password
                endpoint: http://localhost:9000

swagger:
  authorization-url: http://localhost:9003/realms/my-realm/protocol/openid-connect/auth

spring:
    application:
        name: map-report-backend

    config:
        activate:
            on-profile: local
    data:
        mongodb:
            host: localhost
            port: 27017
            username: root
            password: example
            database: admin
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:9003/realms/my-realm
logging:
    level:
        org:
            springframework:
                web: debug
        openbuildright: debug

