
spring:
    application:
        name: map-report-backend
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
server:
    port: 8080
---
openbuildright:
    reportmapper:
hibernate:
    hbm2ddl:
        auto: create-drop
spring:
    config:
        activate:
            on-profile: local
---
openbuildright:
    reportmapper:
spring:
    application:
        name: map-report-backend
    config:
        activate:
            on-profile: local-docker-compose
    data:
        mongodb:
            host: localhost
            port: 27017
            username: root
            password: example
            database: admin


