
spring:
    application:
        name: map-report-backend
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
server:
    port: 8080
---
openbuildright:
    reportmapper:
        objectstore:
            image:
                max-width: 500
                max-height: 500
                normalize-image: true
            minio:
                bucket: dev
                access-key: minio_root_user
                secret-key: minio_root_password
                endpoint: http://localhost:9000

spring:
    application:
        name: map-report-backend

    config:
        activate:
            on-profile: local
    data:
        mongodb:
            host: localhost
            port: 27017
            username: root
            password: example
            database: admin
logging:
    level:
        org:
            springframework:
                web: debug
        openbuildright: debug

